name: main

on:
  push:
    branches: [main]

env:
  AWS_REGION: eu-west-2
  CI: true

jobs:

  build:

    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      
      - run: npm install
      - run: npm test
      - run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify identity
        run: aws sts get-caller-identity

      - run: npm run deploy:production
